# Generated by Django 5.0.7 on 2024-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_otp_customuser_otp_expiry_and_more'),
        ('products', '0003_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
